// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOnj3NZWdO7Aog8YEQ6H4q8LJCnmMlAcc',
    appId: '1:246940218145:android:ff1e745d0a6d932d04c460',
    messagingSenderId: '246940218145',
    projectId: 'max-gym-bf441',
    storageBucket: 'max-gym-bf441.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1cI3_D5GZbOtYMiTTgGvSFhjjfyKzz8',
    appId: '1:246940218145:ios:bd3ccb44d0e3064704c460',
    messagingSenderId: '246940218145',
    projectId: 'max-gym-bf441',
    storageBucket: 'max-gym-bf441.firebasestorage.app',
    iosBundleId: 'com.example.maxGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ1cI3_D5GZbOtYMiTTgGvSFhjjfyKzz8',
    appId: '1:246940218145:ios:14780b727ad4202604c460',
    messagingSenderId: '246940218145',
    projectId: 'max-gym-bf441',
    storageBucket: 'max-gym-bf441.firebasestorage.app',
    iosBundleId: 'maxgym.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQflYB6ZhJFfDz0gwUp62QaCzQU8qoW_I',
    appId: '1:246940218145:web:1bf07c807d764f3404c460',
    messagingSenderId: '246940218145',
    projectId: 'max-gym-bf441',
    authDomain: 'max-gym-bf441.firebaseapp.com',
    storageBucket: 'max-gym-bf441.firebasestorage.app',
    measurementId: 'G-LVSV1S0NJV',
  );

}